export enum CarInsuranceFormType {
    insuranceType = "Variante",
    movementType = "Antriebsart",
    brand = "Marke",
    modelName = "Modellbezeichnung",
    enginePower = "Motorleistung in kW (gesamt)",
    carPrice = "Listenneupreise inkl. USt und NoVA",
    specialEquipment = "Sonderaustattung in EUR",
    leasing = "Leasing",
    creationDate = "Baujahr/Erstzulassung",
    amountOfSeats = "Anzahl der Sitzplätze",
    registrationDistrict = "Zulassungsbezirk",
    bonusLevel = "Bonusstufe",
    kmPerYear = "Kilometerleistung pro Jahr",
    paymentType = "Zahlart",
    paymentFrequency = "Zahlungsfrequenz",
    salutation = "Anrede",
    academicTitlePre = "Akad. Grad (vorangestellt)",
    firstname = "Vorname",
    lastname = "Nachname",
    academicTitlePost = "Akad. Grad (nachgestellt)",
    citizenship = "Staatsbürgerschaft",
    birthday = "Geburtstag",
    job = "Beruf",
    address = "Adresse",
    doornumber = "Hausnummer/Stiege/Stock/Tür",
    postalCode = "PLZ",
    city = "Ort",
    email = "E-Mail Adresse",
    phoneNumber = "Telefonnummer",
    orderAccepted = "Beratungsauftrag akzeptiert"
}

export const carInsuranceFormTypes = Object.values(CarInsuranceFormType)